#!/bin/sh

if [ $# -eq 0 ]; then
    sunbeam query -n '{
        title: "Docker",
        commands: [
            {
                name: "list-containers",
                title: "List Containers",
                mode: "view"
            }
        ]
    }'
    exit 0
fi

if [ "$1" = "list-containers" ]; then
    docker container ls --format '{{json .}}' | sunbeam query -s 'map({
        title: .Names,
        subtitle: .Image,
        accessories: [.State, .Status],
        actions: []
    }) | {type: "list", items: .}'
fi

